apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: un7hj1g95-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:47a820ec6910cbb704f5772e35909bbc4d8237fb@sha256:009df73fcd0f6a7fb5e3f73b40e52790ed7240c729f723b258bd70e023b3f957
          name: container-image
