apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: un7hj1g95-go
  janus-idp.io/tekton: un7hj1g95-go
  backstage.io/kubernetes-id: un7hj1g95-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: un7hj1g95-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
