apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: un7hj1g95-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: un7hj1g95-go 
  name: un7hj1g95-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: un7hj1g95-go 
